name: Pandoc slides

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
       
    - name: Generate HTML slides with Pandoc
      uses: docker://pandoc/latex:2.9
      with:
        args: "--biblio src/bib/main.bib --csl src/bib/ieee.csl --include-in-header src/css/slides.css --mathjax -V theme=simple -s --slide-level 2 -t revealjs -s -o src/index.html src/index.md -V revealjs-url=https://unpkg.com/reveal.js@3.9.2/"

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: src

    - name: Remove extra files
      run: |
       rm -f ./src/index.md ./src/Makefile
 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src
