name: Pandoc slides

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: mkdir
      run: |
       mkdir public
       
    - name: Generate HTML slides with Pandoc
      uses: docker://pandoc/latex:2.9
      with:
        args: "--mathjax -V theme=simple -s --slide-level 2 -t revealjs -s -o index.html index.md -V revealjs-url=https://unpkg.com/reveal.js@3.9.2/"

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: .

    - name: Remove extra files
      run: |
       rm -f .gitmodules README.md LICENSE index.md
 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
